services:
  - type: web
    name: gold-rate-api
    env: node
    plan: free
    buildCommand: |
      npm ci
      npx playwright install chromium
    startCommand: node index.js
    autoDeploy: true
